// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ovwtfvbxfycicxzmeoim.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im92d3RmdmJ4ZnljaWN4em1lb2ltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMjMzNTgsImV4cCI6MjA2OTc5OTM1OH0.u2vC-iIjPrV-BODr2m3uOGlQgzzydqfn4N9s_pkMNgI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});